name: myhub_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.23+24

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6
  dio: ^3.0.8
  modal_progress_hud: ^0.1.3
  toast: ^0.1.5
  division: ^0.8.7+2
  firebase_messaging: ^6.0.9
  flutter_app_badger: ^1.1.2
  sweetalert: ^0.0.1
  badges: ^1.1.0
  table_calendar: ^2.2.2
  fancy_on_boarding: ^1.4.0
  gradient_app_bar: ^0.1.3
  flutter_slidable: ^0.5.5
  carousel_slider: ^1.4.1
  #geolocator: ^5.2.1
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.22+1
  image_picker: ^0.6.1+4
  http: ^0.12.0+4
  url_launcher: ^5.4.2
  basic_utils: ^2.5.0
  webview_flutter: ^0.3.21
  intl: ^0.16.1
  merge_map: ^1.0.2
  google_sign_in: ^4.5.1
  percent_indicator: ^2.1.5
  package_info: ^0.4.1
  store_redirect: ^1.0.2
  calendar_strip: ^1.0.6
  aad_oauth: ^0.1.9
  cached_network_image: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg
    - images/logo_scm.png
    - images/logo_scm_white.png
    - images/helpImage.png
    - images/header_konfirmasi.png
    - images/conform_attd.png
    - images/leave_head.png
    - images/building.png
    - images/02103240.png
    - assets/data/records.json
    - assets/images/
    - assets/images/Clipboard-empty.png
    - assets/images/microsoft.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

